### PR TITLE
fix scripts/in_list.pl

### PR DESCRIPTION
**Pull request by shenwei356**
Before fix, error came:

```
Can't modify non-lvalue subroutine call at fasta_utilities/in_list.pl line 57, <$_[...]> line 2.
```

### CODE REVIEW

**Comment by jimhester** [comment]
Couldn't this just be changed to

``` perl
my ($header) = split /[\s\/]+/,$seq->header;
```

**Comment by shenwei356** [comment]
That's not enough, you need change at least two lines:

From 

```
  ($seq->header) = split /[\s\/]+/,$seq->header;
  my $found = exists $headers{$seq->header};
```

To

```
  my ($header) = split /[\s\/]+/,$seq->header;
  my $found = exists $headers{$header};
```

My changes were due to I preferred using a global variant out side the while loop.

**Comment by jimhester** [comment]
Yes sorry I should have been explicit and showed both lines. My question was why you were leaking the (`$h`) variables scope?

**Comment by shenwei356** [comment]
I'll propose another one, or you can change it by yourself.

**Pull request closed without merging**
